# Generated by Django 3.1.7 on 2021-02-25 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
