# Generated by Django 3.1.7 on 2021-02-26 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210225_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
