# Generated by Django 3.1.7 on 2021-02-26 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210226_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
