# Generated by Django 3.1.7 on 2021-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210226_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by_template',
            field=models.BooleanField(default=False),
        ),
    ]
